### ISSUE TITLE
Como fazer a instalação no Wordpress?

### ISSUE THREAD

**Issue by Wulong95** [exatasmente/pmpro-pagseguro#3]
Qual o passo a passo para instalar e funcionamento no Wordpress, preciso utilizar o PagSeguro no PMPro e só encontrei a sua solução.

Grato.

**Comment by exatasmente** [comment]
No momento o plugin está em processo de desenvolvimento.
Abaixo está o link para acompanhar o andamento:
 [Projeto ](https://github.com/exatasmente/pmpro-pagseguro/projects/1)
