### ISSUE TITLE
Erro ao assinar o plano com o Pag Seguro: 10026

### ISSUE THREAD

**Issue by mmvestudio** [exatasmente/pmpro-pagseguro#4]
Ao tentar fazer um pagamento aparece o seguinte erro: Erro ao assinar o plano com o Pag Seguro: 10026
 
Quando tento fazer usando o Sandbox aparece uma tela branca com as linhas:
array(24) { ["url"]=> string(127) "https://ws.sandbox.pagseguro.uol.com.br/pre-approvals/?email=marcelo%40mmvestudio.com.br&token=[Informações privadas] ["content_type"]=> string(58) "application/vnd.pagseguro.com.br.v3+xml;charset=ISO-8859-1" ["http_code"]=> int(200) ["header_size"]=> int(417) ["request_size"]=> int(1250) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(4.625689) ["namelookup_time"]=> float(2.9E-5) ["connect_time"]=> float(0.009513) ["pretransfer_time"]=> float(0.037296) ["size_upload"]=> float(964) ["size_download"]=> float(144) ["speed_download"]=> float(31) ["speed_upload"]=> float(208) ["download_content_length"]=> float(144) ["upload_content_length"]=> float(0) ["starttransfer_time"]=> float(4.62565) ["redirect_time"]=> float(0) ["redirect_url"]=> string(0) "" ["primary_ip"]=> string(12) "[Informações privadas]" ["certinfo"]=> array(0) { } ["body"]=> array(1) { ["code"]=> string(32)"[Informações privadas]" } }

**Comment by exatasmente** [comment]
O plugin está em desenvolvimento, no momento não existe um versão de produção, essas telas são para debug.
